accounts/urls.py
# /accounts/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from base import settings
from accounts.views import profile_view, guest_view, register_view, login_view, logout_view


app_name = 'accounts'

urlpatterns = [
    path('', profile_view, name="profile_view"),
    path('guest/', guest_view, name="guest_view"),
    path('profile/', profile_view, name="profile_view"),
    path('register/', register_view, name="register_view"),
    path('login/', login_view, name="login_view"),
    path('logout/', logout_view, name="logout_view"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from base import settings
from .views import *


app_name = 'todo'

urlpatterns = [
    path('', home, name="todo_home"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime
from django.contrib.auth.models import User

now = datetime.now() # current date and time
time = now.strftime("%H:%M:%S")


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    location = models.CharField(max_length=30, blank=True, null=True)
    employee_number = models.IntegerField()
    work_shift = models.IntegerField(default=2)

    class Meta:
        ordering = ['user']
        verbose_name_plural = "User Profiles"
        verbose_name = "User Profile"

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)



class Account(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Accounts"
        verbose_name = "Account"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Account, self).save(*args, **kwargs)

todo/models.py
from datetime import datetime

from django.db import models
from django.template.defaultfilters import slugify

now = datetime.now()  # current date and time
time = now.strftime("%H:%M:%S")


class Image(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(default="assets/default.png", blank=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Images"
        verbose_name = "Image"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Image, self).save(*args, **kwargs)


class Todo(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    task = models.CharField(max_length=200, blank=True, null=True)
    completed = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['task']
        verbose_name_plural = "Tasks"
        verbose_name = "Task"

    def __str__(self):
        return self.task

    def save(self, *args, **kwargs):
        self.slug = slugify(self.task)
        super(Todo, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from accounts.models import UserProfile


class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'location',
            'employee_number',
        )

todo/forms.py
from todo.models import Image
from django import forms


class Form(forms.ModelForm):
    class Meta:
        model = Image
        fields = [
            'name',
            'image',
        ]

accounts/views.py
# /accounts/views.py
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.shortcuts import render
from base.settings import LOGIN_VIEW


def guest_view(request):
    context = {}
    return render(request, 'accounts/guest.html', context)


@login_required(login_url="/accounts/login/")
def profile_view(request):
    context = {}
    return render(request, 'accounts/profile.html', context)


def register_view(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            # Log User in
            login(request, user)
            return redirect('accounts:profile_view')
        else:
            form = UserCreationForm()

    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Log User in
            user = form.get_user()
            login(request, user)
            return redirect(LOGIN_VIEW)
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('accounts:guest_view')
    return render(request, 'accounts/guest.html')

todo/views.py
from django.shortcuts import render

from .models import Image, Todo


def home(request):
    count_all = Todo.objects.all().count()
    not_complete = Todo.objects.filter(completed=False).count()
    complete = Todo.objects.filter(completed=True).count()
    tasks = Todo.objects.all()
    context = {
        "tasks": tasks,
        "count_all": count_all,
        "complete": complete,
        "not_complete": not_complete,
    }
    return render(request, 'todo/home.html', context)

accounts/templates/accounts/base.html
{% load static %} {% load humanize %} {% load icons %} {% load widget_tweaks %} {% load accounts_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/b4ac6ef2b3.js"></script>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom SASS (CSS) File -->
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">


    <title>Home App</title>
  </head>
  <header>

  </header>
  <body>
    {% block content %} {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'accounts/js/accounts.js' %}"></script>

  </body>
</html>

accounts/templates/accounts/guest.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid p-5">
    <h3 class='text-center'>Guest</h3>
</div>
<div class="container-fluid text-center">
    <a href="{% url 'accounts:register_view' %}" class="mb-2 col-sm-2 btn btn-primary">Register</a>
    <a href="{% url 'accounts:login_view' %}" class="mb-2 col-sm-2 btn btn-primary">Login</a>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center">Account Login</h3>
    <form action="{% url 'accounts:login_view' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {% if request.GET.next %}
            <input type="hidden" value="{{ request.GET.next }}">
        {% endif %}
        <br>
        <input class="col-sm-2 btn btn-primary" type="submit" value="Login">
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid pt-3">
    <h3 class="text-center">{{user.first_name}} {{user.last_name}}'s Profile</h3>
</div>
<div class="container-fluid text-center">
<a href="{% url 'home' %}" class="btn btn-primary">Check Messages</a>
</div>
<div class="container-fluid">
<h3 class="text-center">Employee Number</h3>

<img src="" alt="">
</div>
<div class="container-fluid">
    <div class="container-fluid row">
        <div class="ml-4 col-sm-12 col-md-6 col-lg-3 card mt-3 pt-2">
        <h3 class="text-center"><span>{{ user.first_name }} {{user.last_name}}</span></h3>
        <h5 class="text-center">Employee #: 
        <button type="button" class="btn btn-primary btn-small p-1" data-toggle="modal" data-target="#employee_number{{ user.employee_number }}">
  Show
</button>
        </h5>
        <h5 class="text-center">G-South Crane #: 
        <button type="button" class="btn btn-primary btn-small p-1" data-toggle="modal" data-target="#crane20758">
  Show
</button>
        </h5>
    </div>
    </div>
</div>

<!-- Button trigger modal -->


<!-- EMPLOYEE NUMBER Modal -->
<div class="modal fade" id="employee_number{{ user.employee_number }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">{{user.first_name}} {{user.last_name}} ({{ user.profile.employee_number }})</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="../../../media/employee_number/Lee%20Laing.png" alt="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary p-1" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- CRANE NUMBER Modal -->
<div class="modal fade" id="crane20758" tabindex="-1" role="dialog" aria-labelledby="crane20758Title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="crane20758Title">{{user.first_name}} {{user.last_name}} (20758)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img width="100%" src="../media/inspections/crane-20758.png" alt="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary p-1" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center pb-5">Register New Account</h3>
    <form action="{% url 'accounts:register_view' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <input class="col-sm-2 btn btn-primary" type="submit" value="Register">
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/user_badge.html
<div class="container-fluid">
<h4 class="text-center">{{ user.first_name }} {{ user.last_name }}</h4>
</div>

todo/templates/todo/base.html
{% load static %} {% load humanize %} {% load widget_tweaks %} {% load todo_tags %}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<!--Import Google Icon Font-->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>

	<!-- font awesome -->
	<script src="https://kit.fontawesome.com/b4ac6ef2b3.js" crossorigin="anonymous"></script>


	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	
	<!-- Custom SASS (CSS) File -->
	<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">


</head>
<header>

</header>
<body>
{% block content %} {% endblock content %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="{% static 'todo/js/todo.js' %}"></script>

</body>
</html>

todo/templates/todo/base_m.html
{% load static %} {% load humanize %} {% load icons %} {% load widget_tweaks %} {% load todo_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/b4ac6ef2b3.js"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    {% comment %} <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> {% endcomment %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom SASS (CSS) File -->
    <link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">

    <title>todo App</title>
</head>
<header>

</header>

<body>

    {% block content %} {% endblock content %}

    {% comment %} <!-- Compiled Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> {% endcomment %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'todo/js/todo.js' %}"></script>
</body>

</html>

todo/templates/todo/components/now.html
<div class="container-fluid mt-3 text-center">
	<span class='text-center' id="date">{% now "F n, Y" %}</span>
	<span class="clock text-center" id="clock">00:00:00</span>
	<span class="hex-color text-center" id="hex-color">#000000</span>
</div>

todo/templates/todo/home.html
{% extends 'todo/base.html' %}
{% load static %}
{% load icons %}

{% block content %}
	<head><title>todo</title></head>
	<div class="container-fluid mt-3">
		<h1 class="text-center">Todo's ({{ count_all }})</h1>
		<br>
		<div class="not_completed text-center">
			Not Completed ({{ not_complete }})
		</div>
		<div class="container">
			<ul>
				{% for task in tasks %}
					{% if not task.completed %}
						<li class="task">{{ task.task }}</li>
						<span><a class="done btn btn-primary">Done</a></span>
						<span><a class="edit btn btn-success">Edit</a></span>
						<span><a class="delete btn btn-danger">Delete</a></span>
					{% endif %}
				{% endfor %}
			</ul>
		</div>
		<div class="completed text-center">
			Completed ({{ complete }})
		</div>

		<div class="container">
			<ul>
				{% for task in tasks %}
					{% if task.completed %}
						<li class="task">{{ task.task }}</li>
					{% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock content %}